### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/xdecor#70]
Reminder for myself until the next engine release : 

- [ ] Use of texture atlases on some nodes using https://github.com/minetest/minetest/commit/7057c1
- [ ] Use a 2D sheet for animated textures using https://github.com/minetest/minetest/commit/a07b03

**Comment by kilbith** [comment]
- [ ] Add a shitload of new enchantments, https://github.com/minetest/minetest/commit/a637107a4e81be88938d68df4deae50e68cf2cd8
- [ ] Rehabilitate 3d_armor enchanting, ~~bitch~~ negotiate a stable API to its author.
- [ ] Add town wooden panels with some hacks to display the town names depending on the pointing angle, https://i.imgur.com/OX0vIQf.png
- [ ] Add fireworks with sounds?
